name = "cool"
license = "MIT"
licenselink = "https://github.com/jgoggles/coolcoolcoolcoolcoolcool.cool/blob/master/themes/cool/LICENSE"
description = "Cool Hugo theme"
tags = ["cool"]
features = ["blog"]
min_version = "0.10"

[author]
  name = "jgoggles"
  homepage = "danweaver.dev"

[original]
  name = "Vimux"
  homepage = "https://github.com/vimux"
